name: Run Batch File

on:
  push:
    branches:
      - main

jobs:
  run-batch-file:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Custom Action
      run: |
        python run_batch_file.py
      working-directory: .github/actions
